export const ROUTES = {
  home: '/',
  products: '/products',
  productDetails: (slug = ':slug') => `/products/${slug}`,
  categories: '/categories',
  categoryDetails: (slug = ':slug') => `/categories/${slug}`,
  cart: '/cart',
  wishlist: '/wishlist',
  about: '/about',
  contact: '/contact',
  sizeGuide: '/size-guide',
  trackOrder: '/track-order',
  profileTab: (tab: 'profile' | 'track' = 'profile') =>
    tab === 'track' ? '/dashboard/profile?tab=track' : '/dashboard/profile',
  checkout: '/checkout',
  checkoutPayment: '/checkout/payment',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  verifyEmail: '/verify-email',
  dashboard: '/dashboard',
  dashboardOrders: '/dashboard/orders',
  dashboardOrderDetails: (id = ':id') => `/dashboard/orders/${id}`,
  dashboardProfile: '/dashboard/profile',
  dashboardAddresses: '/dashboard/addresses',
  adminRoot: '/admin',
  adminDashboard: '/admin/dashboard',
  adminAnalytics: '/admin/analytics',
  adminProducts: '/admin/products',
  adminOrders: '/admin/orders',
  adminInventory: '/admin/inventory',
  adminUsers: '/admin/users',
  adminSettings: '/admin/settings',
  notFound: '*',
} as const;

export type RouteKey = keyof typeof ROUTES;
